# Generated by Django 5.2 on 2025-04-19 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('frecuencia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_base', to='productos.producto')),
                ('producto_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_recomendado', to='productos.producto')),
            ],
            options={
                'db_table': 'productorecomendacion',
                'constraints': [models.CheckConstraint(condition=models.Q(('producto_base', models.F('producto_recomendado')), _negated=True), name='different_products')],
                'unique_together': {('producto_base', 'producto_recomendado')},
            },
        ),
    ]
