# Generated by Django 5.2 on 2025-04-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('numero_ci', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=14, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('puntos_acumulados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descuentos_disponibles', models.IntegerField(blank=True, null=True)),
                ('descuentos_utilizados', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('numero_ci', models.IntegerField()),
                ('telefono', models.CharField(max_length=14)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='TipoAccionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('CrearProducto', 'Crear Producto'), ('ActualizarProducto', 'Actualizar Producto'), ('CrearVenta', 'Crear Venta'), ('CancelarVenta', 'Cancelar Venta'), ('ActualizarStock', 'Actualizar Stock'), ('CrearCliente', 'Crear Cliente'), ('ActualizarCliente', 'Actualizar Cliente'), ('CrearCategoria', 'Crear Categoría'), ('GenerarReporte', 'Generar Reporte'), ('ConsultarProducto', 'Consultar Producto'), ('ConsultarCliente', 'Consultar Cliente'), ('ConsultarUsuarios', 'Consultar Usuarios'), ('ConsultarCategoria', 'Consultar Categoria'), ('ActualizarCategoria', 'Actualizar Categoría'), ('CrearPersonal', 'Crear Personal'), ('ConsultarPersonal', 'Consultar Personal'), ('ActualizarPersonal', 'Actualizar Personal'), ('ConsultarVenta', 'Consultar Venta'), ('ConsultarHistorial', 'Consultar Historial'), ('CrearNotificacion', 'Crear Notificacion'), ('ConsultarNotificacion', 'Consultar Notificacion'), ('ActualizarNotificacion', 'Actualizar Notificacion'), ('CrearComandos', 'Crear Comandos'), ('ConsultarComandos', 'Consultar Comandos')], max_length=50)),
            ],
            options={
                'db_table': 'tipoaccionbitacora',
            },
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convertida_venta', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
            options={
                'db_table': 'historialbusqueda',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('almacenista', 'Almacenista')], default='cliente', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente')),
                ('personal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personal')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('alerta_stock', 'Alerta de Stock'), ('sistema', 'Sistema'), ('venta', 'Venta')], default='sistema', max_length=50)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_direccion', models.GenericIPAddressField()),
                ('tipo_accion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.tipoaccionbitacora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
    ]
